// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maths.proto

package ds.examples.maths;

public interface ConvertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maths.ConvertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>int32 base = 2;</code>
   */
  int getBase();
}
