// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maths.proto

package ds.examples.maths;

public final class MathServiceImpl {
  private MathServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_ConvertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_ConvertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_ConvertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_RandomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_RandomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_NumberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_NumberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_NumberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_NumberMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013maths.proto\022\005maths\"B\n\016ConvertMessage\022\016" +
      "\n\006number\030\001 \001(\t\022\020\n\010fromBase\030\002 \001(\005\022\016\n\006toBa" +
      "se\030\003 \001(\005\"/\n\017ConvertResponse\022\016\n\006number\030\001 " +
      "\001(\t\022\014\n\004base\030\002 \001(\005\":\n\rRandomRequest\022\017\n\007nu" +
      "mbers\030\001 \001(\005\022\013\n\003min\030\002 \001(\005\022\013\n\003max\030\003 \001(\005\" \n" +
      "\016NumberResponse\022\016\n\006number\030\001 \001(\005\"\270\001\n\020Calc" +
      "ulateRequest\022\017\n\007number1\030\001 \001(\002\022\017\n\007number2" +
      "\030\003 \001(\002\0224\n\toperation\030\004 \001(\0162!.maths.Calcul" +
      "ateRequest.Operation\"L\n\tOperation\022\014\n\010ADD" +
      "ITION\020\000\022\017\n\013SUBTRACTION\020\001\022\022\n\016MULTIPLICATI" +
      "ON\020\002\022\014\n\010DIVISION\020\003\"4\n\021CalculateResponse\022" +
      "\016\n\006result\030\001 \001(\002\022\017\n\007message\030\002 \001(\t\"\037\n\rNumb" +
      "erMessage\022\016\n\006number\030\001 \001(\0022\242\002\n\013MathServic" +
      "e\022@\n\tcalculate\022\027.maths.CalculateRequest\032" +
      "\030.maths.CalculateResponse\"\000\022H\n\025generateR" +
      "andomNumbers\022\024.maths.RandomRequest\032\025.mat" +
      "hs.NumberResponse\"\0000\001\022C\n\raverageValues\022\024" +
      ".maths.NumberMessage\032\030.maths.CalculateRe" +
      "sponse\"\000(\001\022B\n\013convertBase\022\025.maths.Conver" +
      "tMessage\032\026.maths.ConvertResponse\"\000(\0010\001B&" +
      "\n\021ds.examples.mathsB\017MathServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_maths_ConvertMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maths_ConvertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_ConvertMessage_descriptor,
        new java.lang.String[] { "Number", "FromBase", "ToBase", });
    internal_static_maths_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maths_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_ConvertResponse_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_maths_RandomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_maths_RandomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_RandomRequest_descriptor,
        new java.lang.String[] { "Numbers", "Min", "Max", });
    internal_static_maths_NumberResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_maths_NumberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_NumberResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_maths_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_maths_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", });
    internal_static_maths_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_maths_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_maths_NumberMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_maths_NumberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_NumberMessage_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
